name: GitHub Secrets Demo
on: push
jobs:
  GitHub-Actions-Secrets:
    runs-on: ubuntu-latest
    env:
      TEST_REPO_NAME: ${{ secrets.TEST_REPO_NAME }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: ~/download/path
      - name: Test printing your secret 
        run: |
          echo ${TEST_REPO_NAME};
          printenv
          echo ${{ secrets.TEST_REPO_NAME }}