name: GitHub Secrets Demo
on: pull_request
jobs:
  GitHub-Actions-Secrets:
    runs-on: ubuntu-latest
    env:
        SUPER_SECRET: ${{ secrets.TEST_REPO_NAME }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "testing parameter secret"
          echo "$SUPER_SECRET" >> tmp.txt
          cat tmp.txt
          echo "$SUPER_SECRET"
          echo "testing direct reference secret"
          echo ${{ secrets.TEST_REPO_NAME }} >> tmp.txt
          cat tmp.txt
          echo "${{ secrets.TEST_REPO_NAME }}"
          echo ${{ secrets.TEST_REPO_NAME }}
          echo "testing nonstdin secret"
          s="${{ secrets.TEST_REPO_NAME }}"
          echo $s
          ./secrets.sh "${{ secrets.TEST_REPO_NAME }}"
          ./secrests.sh $SUPER_SECRET &
          ps -ae
