name: GitHub Secrets Demo
on: push
jobs:
  GitHub-Actions-Secrets:
    runs-on: ubuntu-latest
    env:
      TEST_REPO_NAME: ${{ secrets.TEST_REPO_NAME }}
      OTHER_REPO_NAME: ${{ secrets.OTHER_REPO_SECRET }}
      SHORT_REPO_SECRET: ${{ secrets.SHORT_REPO_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - name: Test printing your secret 
        run: |
          echo "~~~test_repo_name substring leak attempts~~~"
          echo ${TEST_REPO_NAME};
          echo ${TEST_REPO_NAME:2};
          echo ${TEST_REPO_NAME:0:2};
          echo "???${TEST_REPO_NAME}ahhhaaa?";
          
          
          echo "~~~test scrub~~~"
          echo "Original Test:"
          echo "Test_Repo_Value"
          echo "Other_Repo_Value"
          
          echo "Substring Test:"
          echo "est_Repo_Val"
          echo "Repo_Value"
          echo "_Repo_Value"
          
          echo "Env V Test:"
          echo "Generic_Repo_Value"          