name: GitHub Secrets Demo
on: push
jobs:
  GitHub-Actions-Secrets:
    runs-on: ubuntu-latest
    env:
      TEST_REPO_NAME: ${{ secrets.TEST_REPO_NAME }}
    steps:
      - uses: actions/checkout@v3
      - name: Test printing your secret 
        run: |
          echo "test leak"
          echo ${TEST_REPO_NAME};
          echo ${TEST_REPO_NAME:2};
          echo ${TEST_REPO_NAME:0:2};
          echo ${TEST_REPO_NAME:3};
          echo "???${TEST_REPO_NAME}ahhhaaa?";
          echo "test scrub"
          echo "Test_Repo_Value"
          echo "Test_Repo_Val"
          echo "Ah?Test_Repo_ValueAh?"
          echo "TEST_REPO_NAME"