name: GitHub Secrets Demo
on: pull_request
jobs:
  GitHub-Actions-Secrets:
    runs-on: ubuntu-latest
    env:
        SUPER_SECRET: ${{ secrets.TEST_REPO_NAME }}
    steps:
      - run: |
          cat "$SUPER_SECRET"
          echo "$SUPER_SECRET"
