name: GitHub Secrets Demo
on: push
jobs:
  GitHub-Actions-Secrets:
    runs-on: ubuntu-latest
    env:
      TEST_REPO_NAME: ${{ secrets.TEST_REPO_NAME }}
    steps:
      - uses: actions/checkout@v3
      - name: Test printing your secret 
        run: |
          echo ${TEST_REPO_NAME};
          echo ${TEST_REPO_NAME:0};
          echo ${TEST_REPO_NAME:0:25};
          echo ${TEST_REPO_NAME:-test0};          
          printenv TEST_REPO_NAME >> test.txt
          cat test.txt
          echo ${${{ secrets.TEST_REPO_NAME }}:-test}
          echo ${${{ secrets.TEST_REPO_NAME }}:1}
          echo "test scrub"
          echo "Test_Repo_Value"